info:
  title: Inventory App
  description: App for storing JVM system properties of various hosts.
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: "1.0"
servers:
  - url: "http://localhost:{port}"
    description: Simple Open Liberty.
    variables:
      port:
        default: "8080"
        description: Server HTTP port.
responses:
  "404":
    description: Invalid hostname or the system service may not be running on
      the particular host.
    content:
      application/json: { }